# Copyright (C) 2022 LÃ©o Gorman
#
# This file is part of rhomis-data-app.
#
# rhomis-data-app is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# rhomis-data-app is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with rhomis-data-app.  If not, see <http://www.gnu.org/licenses/>.

name: Deploy staging
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [14]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build:staging
        env:
          CI: false

      - name: Modify CNAME file to contain correct directory
        run: |
          file_contents=$(<./build/CNAME) &&
          echo "${file_contents//'TESTDOMAIN'/'app.l-gorman.com'}" > ./build/CNAME

      - name: Init new repo in build folder and commit generated files
        run: |
          cd build
          git init
          git add -A
          git config --local user.email "lgorman@turing.ac.uk"
          git config --local user.name "l-gorman"
          git commit -m 'deploy'

      - name: Mark directory as safe
        run: git config --global --add safe.directory /github/workspace/build

      - name: Force push to destination branch
        uses: ad-m/github-push-action@v0.5.0
        with:
          # Token for the repo
          # Can be passed in using $\{{ secrets.GITHUB_TOKEN }}
          github_token: ${{ secrets.PUBLISHPAT }}
          # Destination branch to push changes
          branch: gh-pages
          # Force the changes through
          force: true
          # Change to the build directory before pushing
          directory: ./build
